<nav class="navbar navbar-expand-lg navbar-light bg-dark nav-rounded">
    <a class="navbar-brand pl-5 text-light" href="/"><?= APPTITLE ?></a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto pl-5 mt-2 mt-lg-0 ">
            <li class="nav-item font-weight-bold ">
                <a class="nav-link text-light" href="/">Home</a>
            </li>
            <li class="nav-item font-weight-bold">
                <a class="nav-link text-light" href="/rent">Rent</a>
            </li>
            <li class="nav-item font-weight-bold">
                <a class="nav-link text-light" href="/about">About</a>
            </li>
        </ul>
        <ul class="navbar-nav mx-4">
            <?php if ($currentUser === null): ?>
            <li class="nav-item font-weight-bold align-right">
                <a class="nav-link text-light" href="../user/login">Login</a>
            </li>
            <li class="nav-item font-weight-bold align-right">
                <a class="nav-link text-light" href="../user/register">Register</a>
            </li>
                <?php else :?>
            <?php if($_SESSION['user_type'] === '1') :?>
                <li class="nav-item font-weight-bold align-right">
                    <a class="nav-link text-light" href="/userpage"> Admin </a>
                    <?php else: ?>
                    <li class="nav-item font-weight-bold align-right">
                        <a class="nav-link text-light" href="/userpage"> Userpage </a>
                </li>
            <?php endif; ?>
            <li class="nav-item font-weight-bold align-right">
                <a class="nav-link text-light" href="../user/logout">Logout</a>
            </li>
                <?php endif; ?>
        </ul>
    </div>
</nav>