<nav class="navbar navbar-expand-lg navbar-light bg-primary nav-rounded">
    <a class="navbar-brand pl-5" href="<? URLROOT ?>"><?= APPTITLE ?></a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto pl-5 mt-2 mt-lg-0">
            <li class="nav-item font-weight-bold">
                <a class="nav-link" href="<? URLROOT ?>">Home</a>
            </li>
            <li class="nav-item font-weight-bold">
                <a class="nav-link" href="#">Rent</a>
            </li>
            <li class="nav-item font-weight-bold">
                <a class="nav-link" href="<? URLROOT ?>"/about>About</a>
            </li>
        </ul>
        <ul class="navbar-nav mx-4">
            <li class="nav-item font-weight-bold align-right">
                <a class="nav-link" href="<? URLROOT ?>"/user/login>Login</a>
            </li>
            <li class="nav-item font-weight-bold align-right">
                <a class="nav-link" href="<? URLROOT ?>"/user/register>Register</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-dark btn-light my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>