<?php include 'inc/header.phtml'; ?>
<hr>
<div class="container py-3">
    <div class="jumbotron jumbotron-fluid mx-5 rounded jumbo">
        <h1 class="display-4 ">Car rental website</h1>
        <p id="fade"class="lead">Welcome to our car rental website, checkout news and offers</p>
        <hr class="my-4 hr">
    </div>
</div>
<div class="container">
    <div class="row">
    <?php foreach($cars as $car):?>
        <div class="col-md-4">
        <ul class="list-group ">
        <li class="list-group-item border-0 mx-4">
            <a href="review/?id=<?= $car->getId()?>" class="card-link">
            <img src="/~polaznik17/img/<?=$car->getId() ?>.jpg" width="250" height="300" class="rounded img-responsive">
                <p><?= htmlspecialchars($car->getCarName()) ?></p>
            </a>
        </li>
        </div>
        <?php endforeach;?>
    </div>
</div>
<?php include 'inc/footer.phtml'; ?>
