<?php include 'inc/header.phtml'; ?>
    <div class="container px-5 pt-4">
        <form methd="POST" action="/user/loginSubmit">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" placeholder="Enter your e-mail" class="form-control form-control-lg" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="text" placeholder="Enter your password" class="form-control form-control-lg" name="password">
            </div>
            <button type="submit" class="btn btn-outline-dark btn-light">Login</button>
        </form>
    </div>
<?php include 'inc/footer.phtml'; ?>