<?php include 'inc/header.phtml'; ?>
    <div class="container px-5 pt-4">
        <form method="POST" action="<?= URLROOT ?>user/loginSubmit">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" placeholder="Enter your e-mail" class="form-control form-control-lg" id="email" name="email">
            </div>
            <div class="form-group">
                <label for="pass">Password</label>
                <input type="password" placeholder="Enter your password" class="form-control form-control-lg " id="pass" name="pass">
            </div>
            <button type="submit" class="btn btn-outline-primary btn-light login">Login</button>
        </form>
        <div class="row py-4 px-5">
            <div class="col">
                Dont have account? <button class="btn btn-outline-dark"><a class="link" href="<?= URLROOT ?>user/register"> Register</a></button>
            </div>
        </div>
    </div>
<?php include 'inc/footer.phtml'; ?>

