<?php include 'inc/header.phtml'; ?>
<hr>
<?php if ($currentUser): ?>
    <?php if ($_SESSION['user_type'] === '1' || $_SESSION['user_type'] != '2'): ?>

        <form method="POST" action="<?= URLROOT ?>news/add">
            <div class="form-group">
                <label for="new_post" class="py-3" ></label>
                <input type="text" value="Create news" class="font-weight-bold form-control" disabled>
                <textarea class="form-control" id="new_post" name="new_post" rows="3" placeholder="Create news"></textarea>
                <button type="submit" class="btn btn-outline-dark btn-light my-4 py-3 px-5">Post</button>
            </div>
        </form>
    <?php endif; ?>
<?php endif; ?>
    <hr>
<?php foreach ($news as $post): ?>
    <div class="row">
        <div class="col-lg bg-dark rounded">
            <div class="card rounded card-color">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted"><?= $post->getUserName() ?> (<?= $post->getDate() ?>)</h6>
                    <p class="card-text"><?= htmlspecialchars($post->getContent()) ?></p>
                    <?php if ($currentUser && $currentUser->getId() == $post->getUserId()): ?>
                        <button class="btn btn-outline-danger ">
                            <a href="<?= URLROOT ?>news/delete?id=<?= $post->getId() ?>" class="card-link text-dark">Delete</a>
                        </button>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php include 'inc/footer.phtml'; ?>