<?php include 'inc/header.phtml'; ?>
    <div class="container">
        <form method="POST" action="<? URLROOT ?>user/registerSubmit">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="form-group">
                <label for="firstname">First Name</label>
                <input type="text" class="form-control" id="firstname" name="firstname">
            </div>
            <div class="form-group">
                <label for="lastname">Last Name</label>
                <input type="text" class="form-control" id="lastname" name="lastname">
            </div>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="form-group">
                <label for="pass">Password</label>
                <input type="password" class="form-control" id="pass" name="pass">
            </div>
            <div class="form-group">
                <label for="confirm_pass">Confirm Password</label>
                <input type="password" class="form-control" id="confirm_pass" name="confirm_pass">
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" class="form-control" id="country" name="country">
            </div>
            <div class="form-group">
                <label for="license">Driving License</label>
                <input type="text" class="form-control" id="license" name="license">
            </div>
            <button type="Submit" class="btn btn-light btn-outline-dark">Register</button>
        </form>
        <div class="row">
            Already have account? <a class="link" href="<?= URLROOT ?>user/login"> Log in</a>
        </div>
    </div>
<?php include 'inc/footer.phtml'; ?>