<?php include 'inc/header.phtml'; ?>
<hr>

<div class="row">
    <div class="col">
        <ul class="list-group font-weight-bold">
            <h1 class="display-4"><?= $cars->getCarName()?></h1>
            <p class="lead font-weight-bold">Car Informations</p>
            <li class="bg-dark text-light list-group-item w-25">Name : <?= $cars->getCarName()?> </li>
            <li class="bg-dark text-light list-group-item w-25">Manufacturer : <?= $cars->getManufacturer()?> </li>
            <li class="bg-dark text-light list-group-item w-25">Year : <?= $cars->getCarYear()?> </li>
            <li class="bg-dark text-light list-group-item w-25">Color : <?= $cars->getColor()?></li>
            <li class="bg-dark text-light list-group-item w-25">Kilometers on clock : <?= $cars->getCarKm()?> km</li>
            <li class="bg-dark text-light list-group-item w-25">Engine Type : <?= $cars->getEngine()?></li>
            <hr>
<?php foreach ($reviews as $car): ?>
            <p>User Reviews</p>
            <li class="bg-dark text-light list-group-item w-25">User ratings : <?= $car->getScore()?> / 5</li>
<?php endforeach; ?>
        </ul>

        <hr>
    </div>
</div>


<?php if($currentUser) :?>
<div class="row">
    <div class="col">
        <form method="POST" action="<?= URLROOT ?>review/add">
            <div class="form-group">
                <label for="score">Leave a rating for <?= $cars->getCarName()?></label> <br>
                <select name="score" id="score" class="form-control w-25">
                    <option value="1" >1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select> <br>
                <input type="text" id="car_id" name="car_id" value="<?= $cars->getId()?>" hidden> <br>
                <input type="text" id="user_id" name="user_id" value="<?= $currentUser->getId()?>" hidden> <br>
                <button type="submit" class="btn btn-outline-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
<?php endif;?>
<?php include 'inc/footer.phtml'; ?>