<?php include 'inc/header.phtml'; ?>
<hr>
<div class="container-flex">
    <div>
        <h1 class="display-5 pt-5">Account Information</h1>
    </div>
</div>
<?php if($currentUser): ?>
    <?php if($_SESSION['user_type'] === '1' || $_SESSION['user_type'] != '2'): ?>
        <?php foreach($users as $user) :?>
            <div class="container-flex py-5">
                <div class="row">
                    <div class="col w-25">
                        <div class="form-group">
                            <label for="username">Username
                                <h2><input type="text" class="form-control" value="<?= $user->getUsername()?>" name="username" readonly></h2>
                            </label>
                            <label for="firstname">First Name
                                <h2><input type="text" class="form-control " value="<?= $user->getFirstName()?>" name="firstname" readonly></h2>
                            </label>
                                <label for="lastname">Last Name
                                <h2><input type="text" class="form-control " value="<?= $user->getLastName()?>" name="lastname"readonly></h2>
                            </label>
                    <form action="<?= URLROOT ?>/userpage/update" method="POST" >
                            <div class="form-group w-25">
                                <label for="pass">Current Password</label>
                                <input type="text" class="form-control" id="pass" name="pass" required>
                            </div>
                            <div class="form-group w-25">
                                <label for="new_pass">New Password</label>
                                <input type="text" class="form-control" id="new_pass" name="new_pass" required>
                            </div>
                            <div class="form-group w-25">
                                <label for="confirm_new_pass">Confirm new password</label>
                                <input type="text" class="form-control" id="confirm_new_pass" name="confirm_new_pass" required>
                            </div>
                            <button class="btn btn-outline-primary btn-light" type="Submit">Update</button>
                            <input type="text" value="<?= $currentUser->getId() ?>" name="id" id="id" hidden>
                    </form>
                            <label for="country">Country
                                <h2><input type="text" class="form-control " value="<?= $user->getCountry()?>" name="country" readonly></h2>
                            </label>
                            <label for="pass">License number
                                <h2><input type="text" class="form-control " value="<?= $user->getLicense()?>" name="license" readonly></h2>
                            </label>
                            <label for="usertype">User Type
                                <h2><input type="text" class="form-control " value="<?= $user->getUserType()?>" name="usertype" readonly></h2>
                            </label>
        <?php if ($currentUser && $currentUser->getId()): ?>
                            <?php if($_SESSION['user_type'] === '1' || $_SESSION['user_type'] != '2') : ?>
                                <button class="btn btn-outline-danger btn-light"><a href="<?= URLROOT ?>/userpage/delete?id=<?= $user->getId() ?>" class="">Delete</a></button>
                            <?php endif; ?>
                        </div>
            <?php endif; ?>
                    </div>
                </div>
            </div>
        <hr>
        <?php endforeach; ?>
        <div class="container-flex">
            <div>
                <h1 class="display-5 pt-5">Add new user</h1>
            </div>
        </div>

        <div class="container-flex py-5 w-25">
        <div class="row">
            <div class="col">
                <form method="POST" action="<?= URLROOT ?>/userpage/registerSubmit">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="firstname">First Name</label>
                        <input type="text" class="form-control" id="firstname" name="firstname">
                    </div>
                    <div class="form-group">
                        <label for="lastname">Last Name</label>
                        <input type="text" class="form-control" id="lastname" name="lastname">
                    </div>
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="pass">Password</label>
                        <input type="password" class="form-control" id="pass" name="pass" required>
                    </div>
                    <div class="form-group">
                        <label for="confirm_pass">Confirm Password</label>
                        <input type="password" class="form-control" id="confirm_pass" name="confirm_pass" required>
                    </div>
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" name="country">
                    </div>
                    <div class="form-group">
                        <label for="license">Driving License</label>
                        <input type="text" class="form-control" id="license" name="license">
                    </div>
                    <div class="form-group">
                        <label for="usertype">User type</label>
                        <select name="usertype" id="usertype" class="custom-select">
                            <option value="Admin">Admin</option>
                            <option value="User">User</option>
                        </select>
                    </div>
                    <button type="Submit" class="btn btn-light btn-outline-primary">Add user</button>
                </form>
            </div>
        </div>

        <?php else: ?>

            <?php foreach($users as $user) :?>
        <div class="container-flex py-5">
            <div class="row">
                <div class="col w-25">
                    <form action="<?= URLROOT ?>userpage" method="POST">
                        <label for="username">Username
                            <h2><input type="text" class="form-control" value="<?= $user->getUsername()?>" name="username" readonly></h2>
                        </label>
                        <label for="firstname">First Name
                            <h2><input type="text" class="form-control " value="<?= $user->getFirstName()?>" name="firstname" readonly></h2>
                        </label>
                        <label for="lastname">Last Name
                            <h2><input type="text" class="form-control " value="<?= $user->getLastName()?>" name="lastname" readonly></h2>
                        </label>
                        <div class="form-group w-25">
                            <label for="pass">Current Password</label>
                            <input type="text" class="form-control" id="pass" name="pass" required>
                        </div>
                        <div class="form-group w-25">
                            <label for="new_pass">New Password</label>
                            <input type="text" class="form-control" id="new_pass" name="new_pass">
                        </div>
                        <div class="form-group w-25">
                            <label for="confirm_new_pass">Confirm new password</label>
                            <input type="text" class="form-control" id="confirm_new_pass" name="confirm_new_pass" >
                        </div>
                        <label for="country">Country
                            <h2><input type="text" class="form-control " value="<?= $user->getCountry()?>" name="country" readonly></h2>
                        </label>
                        <label for="pass">License number
                            <h2><input type="text" class="form-control " value="<?= $user->getLicense()?>" name="license" readonly></h2>
                        </label>
                        <input type="hidden" value="<?= $currentUser->getId() ?>" name="id">
                    <?php if ($currentUser && $currentUser->getId()): ?>
                        <button class="btn btn-outline-primary btn-light" type="Submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
            <?php endif; ?>
        <?php endforeach; ?>

    <?php endif; ?>
<?php endif; ?>



<?php include 'inc/footer.phtml'; ?>